### ISSUE TITLE
where is wr used in RCNN.py? 

### ISSUE THREAD

**Issue by Sirius083** [JimLee4530/RCNN#2]
you define a wr variable(which I think is the sharing weight in RNN) in RCL layer ? but I cannot find where it is used.

**Comment by JimLee4530** [comment]
It's my error, sorry. I forget to comment it.
I sharing weight in RCL by set the parameters **reuse=True**

> reuse: Boolean, whether to reuse the weights of a previous layer by the same name.

just like:

```python
import tensorflow as tf

x = tf.random_normal(shape=[10, 32, 32, 3])

conv1 = tf.layers.conv2d(x, 3, [2, 2], padding='SAME', reuse=None, name='conv')
print(conv1.name)
conv2 = tf.layers.conv2d(x, 3, [2, 2], padding='SAME', reuse=True, name='conv')
print(conv2.name)
```
